github: workflows: Update compliance to match what upstream does
Downgrade ClangFormat errors to warnings, and add an empty commit message
check, just like upstream.

Signed-off-by: Johan Hedberg <johan.hedberg@silabs.com>

diff --git a/.github/workflows/compliance.yml b/.github/workflows/compliance.yml
--- a/.github/workflows/compliance.yml
+++ b/.github/workflows/compliance.yml
@@ -34,6 +34,14 @@ jobs:
       run: |
         pip3 install python-magic lxml junitparser gitlint pylint pykwalify yamllint clang-format unidiff
 
+    - name: Check for PR description
+      if: ${{ github.event.pull_request.body == '' }}
+      continue-on-error: true
+      id: pr_description
+      run: |
+        echo "Pull request description cannot be empty."
+        exit 1
+
     - name: Run Compliance Tests
       continue-on-error: true
       id: compliance
@@ -57,19 +65,33 @@ jobs:
           exit 1;
         fi
 
+        warns=("ClangFormat")
         files=($($ZEPHYR_BASE/scripts/ci/check_compliance.py -l))
+
         for file in "${files[@]}"; do
           f="${file}.txt"
           if [[ -s $f ]]; then
-            errors=$(cat $f)
-            errors="${errors//'%'/'%25'}"
-            errors="${errors//$'\n'/'%0A'}"
-            errors="${errors//$'\r'/'%0D'}"
-            echo "::error file=${f}::$errors"
-            exit=1
+            results=$(cat $f)
+            results="${results//'%'/'%25'}"
+            results="${results//$'\n'/'%0A'}"
+            results="${results//$'\r'/'%0D'}"
+
+            if [[ "${warns[@]}" =~ "${file}" ]]; then
+              echo "::warning file=${f}::$results"
+            else
+              echo "::error file=${f}::$results"
+              exit=1
+            fi
           fi
         done
 
         if [ "${exit}" == "1" ]; then
+          echo "Compliance error, check for error messages in the \"Run Compliance Tests\" step"
+          echo "You can run this step locally with the ./scripts/ci/check_compliance.py script."
+          exit 1;
+        fi
+        if [ "${{ steps.pr_description.outcome }}" == "failure" ]; then
+
+          echo "PR description cannot be empty"
           exit 1;
         fi
